### ISSUE TITLE
Misc Items / Group Items

### ISSUE THREAD

**Issue by Blzd87** [isaaclepes/Scientific-Sorting-System#1]
Hello,

Is it possible to have a Misc setup and grouping items? like all stone stairs into one chest, all wooden stairs into one chest etc?

I understand i can add more hoppers behind the chest and add the item in the frames but that would take up too much space.?

these two features which the old version had plus your new version together would make the ultimate sorting system

**Comment by isaaclepes** [comment]
This would be easy enough to implement, but I will create a branch for testing as it will add a lot more commands to be executed and may cause some server lag.

Some notes:

  Consider order of operations here.  Datapacks are rather linear, so I would need to either prioritize 1:1 sorting or categorical.  First item frame to match will get all of the items for it's type.

Example:
  If stairs are sorted first, no 'single stair' sorter, say Acacia would function.
  If stairs are sorted second, then the 'category' sorter would never receive Acacia stairs that have a 1:1 sorter created.

  Now this order of operations would need to be determined per-category, as well. If you wanted to have a 'wood' category and a 'stairs' category, as well as an 'acacia stairs' sorter.  You can see how it can become a bit convoluted.

For order of operations, I think it should go from 'most granular' to 'least granular'

Example
1.) Sort 1:1
2.) Sort things like 'Wood stairs'
3.) Sort all 'wooden' items
4.) Sort anything that was not sorted into a catch-all sorter (still will not sort non-survival mode items)

In all cases, if there is no 'receiver' for an item, the teleport fails.

**Comment by isaaclepes** [comment]
Do you have any thoughts on categories/subcategories?  This is quite nuanced, especially since many items would fit in multiple categories, so I would love some feedback.

My thoughts so far are:

Wood
- Stairs
- Blocks
- Slabs
- Fences & gates
- Misc (buttons, doors, trapdoors, signs)

Stone
- Stairs
- Blocks
- Slabs
- Walls
- Misc (buttons, doors, trapdoors, signs)

Glass
- Blocks
- Panes

Ceramic
- terracotta
- glazed terracotta

Cloth
- Wool
- Bed
- Banner
- Carpet

Items
- Food
- Tools
- Weapons
- Armor
- Misc

**Comment by isaaclepes** [comment]
In the enhancement-testing branch, I have implemented a catch all sort that runs after the main sort routine.  This will move any unsorted items to a sort-target item frame containing any item named "Catch All" (case sensitive).

**Comment by Blzd87** [comment]
After posting that question. I managed to find the sort.mcfunction file and found it quite easy to alter. Left item is what goes to the right side item frame so I just changed all wooden stairs to oak stairs etc. So I managed to start setting up categorised groups for our servers needs. Either way your version of the magis sorting system works amazingly how I wanted the original datapack to work. So thank you for making it awesome.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by isaaclepes** [comment]
I'm glad it helped someone :)

**Comment by Blzd87** [comment]
Np. I guess the only thing that would help is that Catch All feature you mentioned. Can that be added in the current setup? And if so where would I add the line of code?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Blzd87** [comment]
dw i just found your testing version in the branch and found that line of code i can implament into my current sort.mcfunction file..

again thanks for making an awesome system.

**Comment by isaaclepes** [comment]
There is another feature I haven't documented yet.  If an item is on the ground for 2400 ticks, it can be teleported to a Capture Target tagged frame, then sorted. In case you have multiple sorters, this would ensure the item is in range of the correct sorter before sorting.  This can also be used for lost & found, since it should capture an item before the server deletes it at 5000 ticks.

**Comment by Blzd87** [comment]
Oh wow that's cool. I guess I can still use my sort.mcfunction file for that update when it's ready?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by isaaclepes** [comment]
It is currently in the main branch, I just haven't updated the readme.

It is currently limited to overworld, see capture.mcfunction and targetcapture.mcfunction

**Comment by Blzd87** [comment]
I tried using the catch all code in the testing one for catch all. But other random items started going into. My chest? I'm unsure where from as I only have 1 gold block + obsidian teleport setup in a whole world.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Blzd87** [comment]
Do you have a discord?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Blzd87** [comment]
> It is currently in the main branch, I just haven't updated the readme.
> 
> It is currently limited to overworld, see capture.mcfunction and targetcapture.mcfunction

that would explain the items going into the catch all chest as they may have been items on the ground somewere in the overworld.... like chicken eggs lol

**Comment by isaaclepes** [comment]
Check that you are using the 'Catch All' tagger and not the 'Capture Target' one.  Maybe I should name those more distinctly.  I will check the function when I have a moment, in case it is bugged.
